### ISSUE TITLE
Retirar informação "Online/Offline" dos contatos

### ISSUE THREAD

**Issue by Victormwlopes** [rafaelcorreiapoli/shact#37]
To ligado que é muito daora, mas a galera não curtiu. Acham que é uma informação privada meio desnecessária de ser compartilhada

**Comment by rafaelcorreiapoli** [comment]
Ok... :(

**Comment by Victormwlopes** [comment]
hahaha sorry bro :/

**Comment by rafaelcorreiapoli** [comment]
2f5ebaf3eaa8617d87f02b252fd05de2a5511370
closes this
