### ISSUE TITLE
Inserir Solução para rosto não identificado

### ISSUE THREAD

**Issue by Victormwlopes** [rafaelcorreiapoli/shact#38]
O que fazer quando nenhum dos 3 perfis sugeridos é o do rosto na fotografia?
Existe algum sistema de Refresh possível? Ou marcar manualmente caso já for amigo? (Até porque se ainda não é amigo, pode tirar uma nova foto, ou procurar por geolocalização)

**Comment by rafaelcorreiapoli** [comment]
Não existe refresh, os resultados seriam exatamente os mesmos
Não existe método para marcar alguém por amizade/geo... isso havia ficado fora do nosso primeiro Milestone

**Comment by Victormwlopes** [comment]
Saquei. É que cara, de umas 30 conexões que fizemos naquele dia teste, 3 não deram o resultado correto. Querendo ou não é um número meio alto para o erro do app. E considerando que nem todo mundo vai ter o mesmo cuidado na hora de tirar foto, acho que seria importante termos uma solução para apresentar. nem que seja um botão escrito "Nenhum destes rostos", e clicando nele aparece um pop up falando para tirar a foto novamente, manja? Só para não ficar como um buraco destampado no app.

**Comment by Victormwlopes** [comment]
E se com uma pequena base de usuários já temos problemas na leitura dos rostos, tenho medo de como vai ser quando escalarmos para uns 2.500 usuários

**Comment by rafaelcorreiapoli** [comment]
Estava garantido de que todos estavam no raio da geolocalização no momento da foto né?
Pq ele só tenta cruzar os rostos das pessoas das fotos com os rostos de pessoas que estão proximas por geolocalização no momento da foto...
- Quantas fotos tinham cadastradas pra cada pessoa? 
- "Não dar o resultado correto" é a pessoa não aparecer em primeiro ou nem aparecer dentre os 3 resultados? 
- Existe a possibilidade de haverem tagado erroneamente alguém ? (e assim essa pessoa estar com um rosto zuado cadastrado pra ela?)
- Como estava a qualidade das fotos ?

**Comment by rafaelcorreiapoli** [comment]
Cara, de novo:
O app é escalável por causa da técnica da geo. A não ser que tenham 2500 pessoas a 10 metros de você, o fato de existirem 2500 pessoas cadastradas não influencia em nada

**Comment by Victormwlopes** [comment]
Ah, perfeito. Esse era meu medo. Não sei porque eu tinha entendido que quando tinhamos trocado para o SkyBiometry não existia isso mais de geolocalização. Fico MUITO mais aliviado em saber que não seria um problema do sistema, mas sim de alguma possível leseira dos usuários.

**Comment by rafaelcorreiapoli** [comment]
Existe ainda a geolocalização, porém não tem mais aquele conceito de criar um grupo de reconhecimento pois a API do skybiometry permite passar um parametro dizendo com quais usuários vc quer fazer o reconhecimento.. ai eu pego quem ta perto e mando junto com a foto pros rostos serem reconhecidos só de pessoas que estiverem nessa lista...
Enfim, cara, isso não entra no nosso plano do MVP que traçamos antes de eu sair da empresa.
Depois que eu terminar o que combinamos, podemos ver novas features e um modelo negócio pra gente trabalhar, se vocês tiverem interesse
