### ISSUE TITLE
Corrigir Data de Aniversário

### ISSUE THREAD

**Issue by Victormwlopes** [rafaelcorreiapoli/shact#39]
A edição de data de nascimento está muito legal! Porém, ao concluir a alteração, a data de aniversário que aparece está com um dia a menos do cadastrado.

**Comment by rafaelcorreiapoli** [comment]
Ok... foi por causa da hospedagem do servidor em um fusorário diferente

**Comment by Victormwlopes** [comment]
hahaha que brisa!

**Comment by rafaelcorreiapoli** [comment]
8459c5580c8018e6f451364e5b20ddba7d05b2df
closes this.
