### ISSUE TITLE
Ajustar sumiço de "Minhas Fotos"

### ISSUE THREAD

**Issue by Victormwlopes** [rafaelcorreiapoli/shact#40]
No Minhas Fotos do Marcelo não aparece nenhuma foto. Tem como dar uma olhada nisso?

**Comment by rafaelcorreiapoli** [comment]
Preciso do login e senha

**Comment by rafaelcorreiapoli** [comment]
Confirmado. vou corrigir assim que possível

**Comment by Victormwlopes** [comment]
marcelo.cassab@shact.com.br
Marcelosc5

**Comment by rafaelcorreiapoli** [comment]
@Victormwlopes 
32c32937c255f899d0a3687d0cb9313425f569c4 closes this
