### ISSUE TITLE
Conexão do App com Facebook

### ISSUE THREAD

**Issue by Victormwlopes** [rafaelcorreiapoli/shact#43]
Precisa ir no facebook liberar um certo número de usuários para usar o nosso app, ou algo assim, certo? Você sabe como faz?

**Comment by rafaelcorreiapoli** [comment]
Não. Isso é pra quando vc tá testando ainda. vc pode manualmente ir lá e liberar umas pessoas pra testarem (ai elas podem fazer login no nosso app com o facebook) mesmo antes de aprovarem nosso app.
Esse nao eh nosso objetivo, eles tem que liberar o nosso app e ai qualquer um vai poder fazer fazer login no nosso app com o face
